// v3 — onboarding option lists, verbatim from data/onboarding.ts + Onboarding.tsx
window.V3OB = {
  GENDER: [
    { val:'male', label:'Male' }, { val:'female', label:'Female' },
    { val:'other', label:'Other' }, { val:'prefer_not_to_say', label:'Skip' },
  ],
  COUNTRIES: ["Argentina","Australia","Austria","Bahrain","Bangladesh","Belgium","Brazil","Canada","Chile","China","Colombia","Denmark","Egypt","Ethiopia","Finland","France","Germany","Ghana","India","Indonesia","Ireland","Israel","Italy","Japan","Kenya","Kuwait","Malaysia","Mexico","Morocco","Nepal","Netherlands","New Zealand","Nigeria","Norway","Oman","Pakistan","Philippines","Poland","Portugal","Qatar","Russia","Saudi Arabia","Singapore","South Africa","South Korea","Spain","Sri Lanka","Sweden","Switzerland","Tanzania","Thailand","Turkey","UAE","United Kingdom","United States","Vietnam"],
  MEAL_PREFERENCE: [
    { val:'non_vegetarian', label:'Non-veg' }, { val:'vegetarian', label:'Vegetarian' },
    { val:'eggetarian', label:'Eggetarian' }, { val:'vegan', label:'Vegan' },
    { val:'pescatarian', label:'Pescatarian' },
  ],
  CUISINE_OPTIONS: [
    ['South Indian','South Asia'],['North Indian','South Asia'],['Mughlai','South Asia'],['Gujarati','South Asia'],
    ['Maharashtrian','South Asia'],['Bengali','South Asia'],['Rajasthani','South Asia'],['Kerala','South Asia'],
    ['Punjabi','South Asia'],['Hyderabadi','South Asia'],['Sri Lankan','South Asia'],['Pakistani','South Asia'],['Nepali','South Asia'],
    ['Chinese','East Asia'],['Japanese','East Asia'],['Korean','East Asia'],['Taiwanese','East Asia'],['Cantonese','East Asia'],['Sichuan','East Asia'],
    ['Thai','Southeast Asia'],['Vietnamese','Southeast Asia'],['Indonesian','Southeast Asia'],['Malaysian','Southeast Asia'],
    ['Filipino','Southeast Asia'],['Singaporean','Southeast Asia'],['Burmese','Southeast Asia'],
    ['Lebanese','Middle East'],['Turkish','Middle East'],['Persian / Iranian','Middle East'],['Arabic','Middle East'],
    ['Israeli','Middle East'],['Yemeni','Middle East'],['Saudi Arabian','Middle East'],
    ['Moroccan','North Africa'],['Egyptian','North Africa'],
    ['Mediterranean','Mediterranean'],['Italian','Mediterranean'],['Greek','Mediterranean'],['Spanish','Mediterranean'],['Portuguese','Mediterranean'],
    ['French','Europe'],['British','Europe'],['German','Europe'],['Scandinavian','Europe'],['Polish','Europe'],['Russian','Europe'],
    ['American','Americas'],['Mexican','Americas'],['Peruvian','Americas'],['Brazilian','Americas'],['Caribbean','Americas'],['Colombian','Americas'],
    ['Ethiopian','Africa'],['Nigerian','Africa'],['West African','Africa'],['East African','Africa'],
    ['Georgian','Caucasus'],['Uzbek / Central Asian','Central Asia'],
  ],
  ALLERGENS: ["Gluten","Dairy","Eggs","Nuts","Peanuts","Shellfish","Fish","Soy","Sesame","Mustard","Sulfites","Corn","Nightshades","Fructose"],
  ALLERGEN_ICONS: { Gluten:'🌾', Dairy:'🥛', Eggs:'🥚', Nuts:'🥜', Peanuts:'🥜', Shellfish:'🦐', Fish:'🐟', Soy:'🫘', Sesame:'🌿', Mustard:'🟡', Sulfites:'⚗️', Corn:'🌽', Nightshades:'🍆', Fructose:'🍬' },
  INGREDIENT_CATEGORIES: [
    { name:'Proteins', items:['Chicken','Eggs','Paneer','Fish','Tuna','Prawns','Mutton','Tofu','Lentils (Dal)','Chickpeas','Kidney Beans','Whey Protein'] },
    { name:'Vegetables', items:['Spinach','Broccoli','Cauliflower','Zucchini','Capsicum','Mushroom','Cabbage','French Beans','Cucumber','Tomato','Onion','Carrot','Pumpkin'] },
    { name:'Fruits', items:['Apple','Banana','Berries','Papaya','Guava','Orange','Watermelon','Pomegranate'] },
    { name:'Nuts & Seeds', items:['Almonds','Walnuts','Chia Seeds','Flaxseeds','Pumpkin Seeds','Cashews'] },
    { name:'Dairy', items:['Curd/Yogurt','Milk','Cheese','Butter','Ghee','Buttermilk'] },
    { name:'Grains & Carbs', items:['Oats','Quinoa','Brown Rice','Sweet Potato','Whole Wheat Roti'] },
  ],
  INGREDIENT_ICONS: {
    Chicken:'🍗', Eggs:'🥚', Paneer:'🧀', Fish:'🐟', Tuna:'🐟', Prawns:'🦐', Mutton:'🥩', Tofu:'🧊',
    'Lentils (Dal)':'🍲', Chickpeas:'🥙', 'Kidney Beans':'🫕', 'Whey Protein':'🥛',
    Spinach:'🥬', Broccoli:'🥦', Cauliflower:'🥦', Zucchini:'🥒', Capsicum:'🫑', Mushroom:'🍄',
    Cabbage:'🥬', 'French Beans':'🫛', Cucumber:'🥒', Tomato:'🍅', Onion:'🧅', Carrot:'🥕', Pumpkin:'🎃',
    Apple:'🍎', Banana:'🍌', Berries:'🫐', Papaya:'🥭', Guava:'🍐', Orange:'🍊', Watermelon:'🍉', Pomegranate:'🫐',
    Almonds:'🌰', Walnuts:'🌰', 'Chia Seeds':'🌱', Flaxseeds:'🌱', 'Pumpkin Seeds':'🌻', Cashews:'🌰',
    'Curd/Yogurt':'🥛', Milk:'🥛', Cheese:'🧀', Butter:'🧈', Ghee:'🫕', Buttermilk:'🥛',
    Oats:'🥣', Quinoa:'🌾', 'Brown Rice':'🍚', 'Sweet Potato':'🍠', 'Whole Wheat Roti':'🫓',
  },
  KITCHEN_EQUIPMENT: ["Stovetop","Oven/OTG","Air Fryer","Microwave","Blender","No equipment"],
  EQUIPMENT_ICONS: { Stovetop:'🔥', 'Oven/OTG':'♨️', 'Air Fryer':'🌀', Microwave:'⏱️', Blender:'🥤', 'No equipment':'🚫' },
  HEALTH_CONDITIONS: ["Diabetes","Thyroid","PCOS","Hypertension","High Cholesterol","IBS","None"],
  GOALS: [
    { val:'eat_healthy', label:'Eat healthy', desc:'Balanced daily nutrition from WHO/RDA — no weight target', generic:true },
    { val:'lose_weight', label:'Lose fat', desc:'Calorie deficit, protein priority, weekly pace' },
    { val:'maintain', label:'Maintain', desc:'Stay at current weight, body recomposition' },
    { val:'gain_muscle', label:'Gain muscle', desc:'Small calorie surplus, high protein' },
    { val:'improve_fitness', label:'Athletic perf', desc:'Maintenance + energy for training, higher carbs' },
    { val:'manage_health', label:'Manage health', desc:'Condition-specific macros, moderate protein' },
  ],
  INTENSITY: [
    { val:'low', label:'Gentle', sub:'0.25 kg/w' },
    { val:'moderate', label:'Steady', sub:'0.5 kg/w' },
    { val:'high', label:'Aggressive', sub:'0.75 kg/w' },
  ],
  ACTIVITY: [
    { val:'sedentary', label:'Sedentary', desc:'Desk job, little exercise' },
    { val:'lightly_active', label:'Light', desc:'Light exercise 1–3 days/week' },
    { val:'moderately_active', label:'Moderate', desc:'Exercise 3–5 days/week' },
    { val:'very_active', label:'Active', desc:'Hard exercise 6–7 days/week' },
  ],
  TRAINING_TYPES: [
    { val:'none', label:'No structured training', desc:'Walking, light activity only' },
    { val:'strength', label:'Strength / gym', desc:'Weight training, resistance work' },
    { val:'endurance', label:'Endurance', desc:'Running, cycling, swimming' },
    { val:'crossfit', label:'CrossFit / HIIT', desc:'High-intensity interval training' },
    { val:'mixed', label:'Mixed', desc:'Combination of strength + cardio' },
  ],
  OCCUPATION: [
    { val:'desk_job', label:'Desk job', desc:'Seated most of the day' },
    { val:'active_job', label:'Active job', desc:'On feet frequently' },
    { val:'manual_labour', label:'Manual work', desc:'Physical labour' },
  ],
  COOKING_STYLE: [{ val:'home', label:'Home' }, { val:'mix', label:'Mix' }, { val:'outside', label:'Outside' }],
  SLEEP_QUALITY: [
    { val:'poor', label:'Poor', sub:'< 6 hrs' }, { val:'average', label:'Average', sub:'6–8 hrs' }, { val:'good', label:'Good', sub:'8+ hrs' },
  ],
  STRESS: [{ val:'low', label:'Low' }, { val:'medium', label:'Medium' }, { val:'high', label:'High' }],
  RECOVERY: [
    { val:'poor', label:'Poor', sub:'Often sore' }, { val:'average', label:'Average', sub:'Normal' }, { val:'excellent', label:'Excellent', sub:'Recovers fast' },
  ],
  HUNGER: [
    { val:'low', label:'Low', sub:'Rarely hungry' }, { val:'medium', label:'Medium', sub:'Normal' }, { val:'high', label:'High', sub:'Often hungry' },
  ],
  ENERGY: [
    { val:'low', label:'Low', sub:'Fatigued' }, { val:'moderate', label:'Moderate', sub:'Normal' }, { val:'high', label:'High', sub:'Energised' },
  ],
  INSULIN: [
    { val:'poor', label:'Poor', sub:'Insulin resistant' }, { val:'average', label:'Average', sub:'Typical' }, { val:'good', label:'Good', sub:'Sensitive' },
  ],
};
