#!/usr/bin/env bash
# ─────────────────────────────────────────────────────────────────────────────
# generate-android-keystore.sh
# ─────────────────────────────────────────────────────────────────────────────
# Generates a 25-year release keystore for the Android app.
#
# This is a ONE-TIME step. Back up the resulting .jks file to at least two
# secure locations (1Password, encrypted USB, password manager vault).
# Losing the keystore = you can never push an update to your existing app
# on Google Play. You would have to publish a brand new app with a new
# package name.
#
# Usage:
#   ./scripts/generate-android-keystore.sh
#
# Output:
#   android/app/diet-plan-release.jks   — the keystore (git-ignored)
#   android/app/keystore.properties     — credentials reference (git-ignored)
#
# After generation, you must:
#   1. Add the keystore to 1Password / a secure password manager.
#   2. Encode the keystore for GitHub Actions:
#        base64 -i android/app/diet-plan-release.jks | pbcopy
#      and paste it into the ANDROID_KEYSTORE_BASE64 repo secret.
#   3. Add keystore password, key alias, key password as repo secrets.
#   4. (Play Console only) Upload the public certificate to Play App Signing.
# ─────────────────────────────────────────────────────────────────────────────

set -euo pipefail

KEYSTORE_PATH="android/app/diet-plan-release.jks"
KEY_ALIAS="diet-plan-release"
VALIDITY_DAYS=9125   # 25 years
DNAME="CN=Diet Plan & Tracker, OU=Engineering, O=Diet Plan, L=City, ST=State, C=US"

# Color output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

print_header() {
  echo ""
  echo -e "${GREEN}═══════════════════════════════════════════════════════════${NC}"
  echo -e "${GREEN}  Android Release Keystore Generator${NC}"
  echo -e "${GREEN}═══════════════════════════════════════════════════════════${NC}"
  echo ""
}

require_tool() {
  if ! command -v "$1" &> /dev/null; then
    echo -e "${RED}✗ Required tool missing: $1${NC}" >&2
    echo "  Install: $2" >&2
    exit 1
  fi
}

print_header

require_tool "keytool" "Install JDK 17+ (brew install --cask temurin@17)"

if [ -f "$KEYSTORE_PATH" ]; then
  echo -e "${YELLOW}⚠  Keystore already exists at $KEYSTORE_PATH${NC}"
  echo "   Refusing to overwrite. Delete it manually if you want to regenerate."
  exit 1
fi

mkdir -p "$(dirname "$KEYSTORE_PATH")"

# Generate a strong random password (32 chars).
# Uses /dev/urandom via `head -c 32` (more reliable than `tr` on macOS).
gen_password() {
  head -c 32 /dev/urandom | base64 | tr -dc 'A-Za-z0-9' | head -c 32
}

STORE_PASS=$(gen_password)
KEY_PASS=$(gen_password)

echo -e "${YELLOW}This will generate a 25-year keystore. You'll see 4 prompts:${NC}"
echo -e "${YELLOW}  1. Keystore password:    ${GREEN}$STORE_PASS${NC}  (use this)"
echo -e "${YELLOW}  2. Re-enter password:    ${GREEN}$STORE_PASS${NC}  (use this)"
echo -e "${YELLOW}  3. Key password:         ${GREEN}$KEY_PASS${NC}  (use this — or press enter to match)${NC}"
echo -e "${YELLOW}  4. Re-enter key pass:    ${GREEN}$KEY_PASS${NC}  (use this)${NC}"
echo ""

# Use env vars so we can pass them to keytool
export KEYSTORE_PATH STORE_PASS KEY_PASS KEY_ALIAS VALIDITY_DAYS DNAME

keytool -genkeypair \
  -keystore "$KEYSTORE_PATH" \
  -alias "$KEY_ALIAS" \
  -keyalg RSA \
  -keysize 4096 \
  -validity "$VALIDITY_DAYS" \
  -storepass "$STORE_PASS" \
  -keypass "$KEY_PASS" \
  -dname "$DNAME" \
  -storetype JKS

# Write credentials file for local builds
cat > android/app/keystore.properties <<EOF
# Auto-generated by generate-android-keystore.sh
# KEEP THIS FILE OUT OF GIT.
# For local builds, this file is read by android/app/build.gradle.
# For CI builds, see .github/workflows/android.yml for env-var equivalents.
storeFile=$KEYSTORE_PATH
storePassword=$STORE_PASS
keyAlias=$KEY_ALIAS
keyPassword=$KEY_PASS
EOF

# Extract SHA-256 fingerprint (needed for Play Console / Asset Links)
FINGERPRINT=$(keytool -list -v -keystore "$KEYSTORE_PATH" -storepass "$STORE_PASS" 2>/dev/null | grep "SHA256:" | head -1 | awk '{print $2}')

echo ""
echo -e "${GREEN}✓ Keystore generated:${NC} $KEYSTORE_PATH"
echo -e "${GREEN}✓ Credentials saved:  ${NC} android/app/keystore.properties"
echo -e "${GREEN}✓ SHA-256:            ${NC} $FINGERPRINT"
echo ""
echo -e "${YELLOW}═══════════════════════════════════════════════════════════${NC}"
echo -e "${YELLOW}  NEXT STEPS — DO THESE NOW${NC}"
echo -e "${YELLOW}═══════════════════════════════════════════════════════════${NC}"
echo ""
echo "1. BACK UP THE KEYSTORE. Save $KEYSTORE_PATH to:"
echo "   • 1Password / Bitwarden / KeePassXC vault"
echo "   • Encrypted USB drive (offline)"
echo "   • Encrypted cloud storage (e.g. Google Drive encrypted container)"
echo ""
echo "2. Add these to 1Password as a 'Server' item:"
echo "   • Android Keystore password:  $STORE_PASS"
echo "   • Key alias:                  $KEY_ALIAS"
echo "   • Key password:               $KEY_PASS"
echo ""
echo "3. For GitHub Actions, encode the keystore and add to repo secrets:"
echo "   $ base64 -i $KEYSTORE_PATH | pbcopy   # macOS"
echo "   $ base64 -i $KEYSTORE_PATH | xclip    # Linux"
echo ""
echo "   Then add these secrets in Settings → Secrets → Actions:"
echo "   • ANDROID_KEYSTORE_BASE64   (paste from above)"
echo "   • ANDROID_KEYSTORE_PASSWORD = $STORE_PASS"
echo "   • ANDROID_KEY_ALIAS         = $KEY_ALIAS"
echo "   • ANDROID_KEY_PASSWORD      = $KEY_PASS"
echo ""
echo "4. For Google Play App Signing, you need the upload-key certificate"
echo "   fingerprint. The SHA-256 is: $FINGERPRINT"
echo "   Upload this to Play Console → Setup → App integrity → App signing."
echo ""
echo -e "${RED}⚠  If you lose the keystore file, you can NEVER push updates to"
echo -e "   the existing Play Store listing. You will have to publish a new"
echo -e "   app under a new package name.${NC}"
